version: '3'
services: 
  pawsmongodb:
    image: mongo:latest
    container_name: "pawsmongodb"
    environment:
      - MONGO_DATA_DIR=/var/lib/mongodb
      - MONGO_LOG_DIR=/var/log/mongodb
    volumes:
       - /var/lib/mongodb:/var/lib/mongodb
    ports:
       - 27017:27017
    command: mongod --smallfiles --logpath=/var/log/mongodb/mongodb.log # --quiet
  
  # mongo-seed:
  #   build: ./mongo-seed
  #   links:
  #     - pawsmongodb

  pawsserver:
    container_name: "pawsserver"
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    image: pawsserver
    ports:
      - "9090:9090"
    links:
      - pawsmongodb
    depends_on:
      - pawsmongodb
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    links:
      - pawsserver