// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paws_grpc.proto

package pawsgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Diary struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Note                 string   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Date                 string   `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Diary) Reset()         { *m = Diary{} }
func (m *Diary) String() string { return proto.CompactTextString(m) }
func (*Diary) ProtoMessage()    {}
func (*Diary) Descriptor() ([]byte, []int) {
	return fileDescriptor_469dac7101011428, []int{0}
}

func (m *Diary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Diary.Unmarshal(m, b)
}
func (m *Diary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Diary.Marshal(b, m, deterministic)
}
func (m *Diary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Diary.Merge(m, src)
}
func (m *Diary) XXX_Size() int {
	return xxx_messageInfo_Diary.Size(m)
}
func (m *Diary) XXX_DiscardUnknown() {
	xxx_messageInfo_Diary.DiscardUnknown(m)
}

var xxx_messageInfo_Diary proto.InternalMessageInfo

func (m *Diary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Diary) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Diary) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Diary) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

// The response message containing the greetings
type DiaryList struct {
	Diaries              []*Diary `protobuf:"bytes,1,rep,name=diaries,proto3" json:"diaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiaryList) Reset()         { *m = DiaryList{} }
func (m *DiaryList) String() string { return proto.CompactTextString(m) }
func (*DiaryList) ProtoMessage()    {}
func (*DiaryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_469dac7101011428, []int{1}
}

func (m *DiaryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiaryList.Unmarshal(m, b)
}
func (m *DiaryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiaryList.Marshal(b, m, deterministic)
}
func (m *DiaryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiaryList.Merge(m, src)
}
func (m *DiaryList) XXX_Size() int {
	return xxx_messageInfo_DiaryList.Size(m)
}
func (m *DiaryList) XXX_DiscardUnknown() {
	xxx_messageInfo_DiaryList.DiscardUnknown(m)
}

var xxx_messageInfo_DiaryList proto.InternalMessageInfo

func (m *DiaryList) GetDiaries() []*Diary {
	if m != nil {
		return m.Diaries
	}
	return nil
}

type FetchParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchParam) Reset()         { *m = FetchParam{} }
func (m *FetchParam) String() string { return proto.CompactTextString(m) }
func (*FetchParam) ProtoMessage()    {}
func (*FetchParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_469dac7101011428, []int{2}
}

func (m *FetchParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchParam.Unmarshal(m, b)
}
func (m *FetchParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchParam.Marshal(b, m, deterministic)
}
func (m *FetchParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchParam.Merge(m, src)
}
func (m *FetchParam) XXX_Size() int {
	return xxx_messageInfo_FetchParam.Size(m)
}
func (m *FetchParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchParam.DiscardUnknown(m)
}

var xxx_messageInfo_FetchParam proto.InternalMessageInfo

type ResultCode struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultCode) Reset()         { *m = ResultCode{} }
func (m *ResultCode) String() string { return proto.CompactTextString(m) }
func (*ResultCode) ProtoMessage()    {}
func (*ResultCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_469dac7101011428, []int{3}
}

func (m *ResultCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCode.Unmarshal(m, b)
}
func (m *ResultCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCode.Marshal(b, m, deterministic)
}
func (m *ResultCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCode.Merge(m, src)
}
func (m *ResultCode) XXX_Size() int {
	return xxx_messageInfo_ResultCode.Size(m)
}
func (m *ResultCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCode proto.InternalMessageInfo

func (m *ResultCode) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Diary)(nil), "pawsgrpc.Diary")
	proto.RegisterType((*DiaryList)(nil), "pawsgrpc.DiaryList")
	proto.RegisterType((*FetchParam)(nil), "pawsgrpc.FetchParam")
	proto.RegisterType((*ResultCode)(nil), "pawsgrpc.ResultCode")
}

func init() { proto.RegisterFile("paws_grpc.proto", fileDescriptor_469dac7101011428) }

var fileDescriptor_469dac7101011428 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x34, 0x51, 0x3b, 0x15, 0x03, 0x63, 0x0f, 0xa1, 0xa7, 0xb0, 0xa7, 0x7a, 0xc9,
	0xa1, 0x42, 0x8f, 0x82, 0xb4, 0x78, 0xf2, 0x50, 0x02, 0x9e, 0x65, 0xcc, 0x0e, 0x75, 0x21, 0x75,
	0xc3, 0xee, 0x4a, 0xf1, 0xe2, 0x6f, 0x97, 0x9d, 0x50, 0x22, 0xbd, 0xbd, 0xf9, 0x76, 0x78, 0xef,
	0xcd, 0x42, 0xd1, 0xd3, 0xc9, 0xbf, 0x1f, 0x5c, 0xdf, 0xd6, 0xbd, 0xb3, 0xc1, 0xe2, 0x4d, 0x04,
	0x71, 0x56, 0x6f, 0x90, 0xef, 0x0c, 0xb9, 0x1f, 0xbc, 0x83, 0xd4, 0xe8, 0x32, 0xa9, 0x92, 0xd5,
	0xac, 0x49, 0x8d, 0xc6, 0x05, 0xe4, 0xe6, 0x48, 0x07, 0x2e, 0x53, 0x41, 0xc3, 0x80, 0x08, 0xd9,
	0x97, 0x0d, 0x5c, 0x4e, 0x05, 0x8a, 0x8e, 0x4c, 0x53, 0xe0, 0x32, 0x1b, 0x58, 0xd4, 0x6a, 0x03,
	0x33, 0xb1, 0x7d, 0x35, 0x3e, 0xe0, 0x03, 0x5c, 0x6b, 0x43, 0xce, 0xb0, 0x2f, 0x93, 0x6a, 0xba,
	0x9a, 0xaf, 0x8b, 0xfa, 0x9c, 0x5f, 0xcb, 0x56, 0x73, 0x7e, 0x57, 0xb7, 0x00, 0x2f, 0x1c, 0xda,
	0xcf, 0x3d, 0x39, 0x3a, 0xaa, 0x0a, 0xa0, 0x61, 0xff, 0xdd, 0x85, 0xad, 0xd5, 0x92, 0xd3, 0x5a,
	0xcd, 0xd2, 0x31, 0x6f, 0x44, 0xaf, 0x7f, 0x21, 0xdb, 0xd3, 0xc9, 0xe3, 0x06, 0xe6, 0x5b, 0xc7,
	0x14, 0x78, 0x38, 0xe6, 0x32, 0x60, 0xb9, 0x18, 0xc1, 0xe8, 0xa8, 0x26, 0xf8, 0x04, 0x85, 0xe4,
	0x3d, 0x77, 0xdd, 0x6e, 0xa8, 0x80, 0xff, 0x56, 0xc7, 0x2a, 0xcb, 0xfb, 0x0b, 0xc7, 0x78, 0x98,
	0x9a, 0x7c, 0x5c, 0xc9, 0x7f, 0x3e, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x9e, 0x96, 0x58,
	0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PawsClient is the client API for Paws service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PawsClient interface {
	CreateDiary(ctx context.Context, in *Diary, opts ...grpc.CallOption) (*ResultCode, error)
	FetchAllDiaries(ctx context.Context, in *FetchParam, opts ...grpc.CallOption) (*DiaryList, error)
}

type pawsClient struct {
	cc *grpc.ClientConn
}

func NewPawsClient(cc *grpc.ClientConn) PawsClient {
	return &pawsClient{cc}
}

func (c *pawsClient) CreateDiary(ctx context.Context, in *Diary, opts ...grpc.CallOption) (*ResultCode, error) {
	out := new(ResultCode)
	err := c.cc.Invoke(ctx, "/pawsgrpc.Paws/CreateDiary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pawsClient) FetchAllDiaries(ctx context.Context, in *FetchParam, opts ...grpc.CallOption) (*DiaryList, error) {
	out := new(DiaryList)
	err := c.cc.Invoke(ctx, "/pawsgrpc.Paws/FetchAllDiaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PawsServer is the server API for Paws service.
type PawsServer interface {
	CreateDiary(context.Context, *Diary) (*ResultCode, error)
	FetchAllDiaries(context.Context, *FetchParam) (*DiaryList, error)
}

func RegisterPawsServer(s *grpc.Server, srv PawsServer) {
	s.RegisterService(&_Paws_serviceDesc, srv)
}

func _Paws_CreateDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Diary)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PawsServer).CreateDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pawsgrpc.Paws/CreateDiary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PawsServer).CreateDiary(ctx, req.(*Diary))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paws_FetchAllDiaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PawsServer).FetchAllDiaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pawsgrpc.Paws/FetchAllDiaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PawsServer).FetchAllDiaries(ctx, req.(*FetchParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _Paws_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pawsgrpc.Paws",
	HandlerType: (*PawsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDiary",
			Handler:    _Paws_CreateDiary_Handler,
		},
		{
			MethodName: "FetchAllDiaries",
			Handler:    _Paws_FetchAllDiaries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paws_grpc.proto",
}
